name: actionlint
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  run-actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: actionlint
        uses: raven-actions/actionlint@v1
        with:
          shellcheck: false
          pyflakes: false
